### ISSUE TITLE
[BUG] Swords disappearing on zombies

### ISSUE THREAD

**Issue by wgtjunior743** [Blackstone-SS13/BLACKSTONE#1024]
## Describe the bug

Not sure if it is a intended mechanic but now swords can get stuck in the chest, if a sword gets stuck in a chest and you cut a zombie throat, the sword that was stuck in the chest is now gone forever since the zombie turns into dust.

## Round ID:

 Round ID: 412 

## Steps to Reproduce:

Make your sword stuck in the zombie chest, then cut the zombie throat, the sword will be gone.

## Additional context

I don't know if the new medical rework is making so swords get stuck in chest , a bastard sword was stuck in a chest the same way a rapier can, i knew that daggers could be stuck in places like head , but this may or not be a new mechanic.

**Comment by erik30015** [comment]
you can take out the sword if you examine the part you hit with it and it embeed, like taking out a leech. the disappearing sucks tough
