### ISSUE TITLE
[BUG] Zombies just die when they become zombies

### ISSUE THREAD

**Issue by Okram0** [Blackstone-SS13/BLACKSTONE#1049]
## Describe the bug
If you wait to rise as a zombie you will die for real the second you reanimate, ive been drowned and this happened, and ive also bleed out and had this happen (both times I was waiting to be zombie)

## Round ID:

I forget but it should be easy to reproduce.

## Steps to Reproduce:

Wait until you become a zombie, itll say the message that you have become a zombie then immediately deathscreen and kill you for real.

**Comment by ChungusGamer666** [comment]
to be fixed
