### ISSUE TITLE
[BUG] Skelelons spawn braindead

### ISSUE THREAD

**Issue by Wintermote** [Blackstone-SS13/BLACKSTONE#1106]
## Describe the bug
Walk over a bush, skelelons spawn, they immediately drop to the ground and do nothing.

## Round ID:
One of the rounds earlier today, I didn't write down the ID.

Current round ID is Axe472-02.24.16, presumably still the same code as earlier today.

## Steps to Reproduce:
1. Walk over a bush
2. Skelelons spawn
3. They drop to the ground and do nothing

**Comment by ChungusGamer666** [comment]
seems skelelons are fixed
