### ISSUE TITLE
[REQUEST] Give Dwarves dark vision.

### ISSUE THREAD

**Issue by Xkallubar** [Blackstone-SS13/BLACKSTONE#1113]
Makes zero sense that the one race that's gonna be spending most of their time underground in dark caves can't see shit. It even says they have poor vision in their description which doesn't make sense considering they're fantasy dwarves.

**Comment by BlueMemesauce** [comment]
actually arent animals that live underground usually blind like moles?

**Comment by Xkallubar** [comment]
> actually arent animals that live underground usually have poor vision like moles? and just cause dwarves decide to live underground dont mean they evolve right away, this process takes thousand of years, and dwarves dont always live underground all the time

Most fantasy dwarves in other games have some form of infravision.

**Comment by ChungusGamer666** [comment]
forget this
