### ISSUE TITLE
[BUG] Sometimes cannot unstick weapon stuck in enemy's body

### ISSUE THREAD

**Issue by singularshamble** [Blackstone-SS13/BLACKSTONE#1116]
## Describe the bug
When in combat and aiming for the opponent's neck, I have sometimes gotten my weapon (knife, sword, dagger) stuck in the neck. Usually this gives the user opportunity to twist the weapon inside the wound, or get the weapon back in hand and rip it out of the wound. But this time I found I could twist my weapon but not get it back. If I move, the weapon disappears from my hand, and if I search the body after, the weapon is not there. This round I have lost 3 weapons, each to a goblin neck,

## Round ID:
Gold480-20.17.40

## Steps to Reproduce:
Playing as Mortician
Get weapon (not one I spawned with)
Turn on Combat Mode (I turned intent to Strong)
Chop/Cut at goblin neck soon after they walked out of portal
Get weapon stuck in neck
Cannot remove it

## Additional context
It might be a gobbo thing idk, I didn't fight any people this round.

**Comment by ChungusGamer666** [comment]
Have not seen this happen in a while, I am convinced it is fixed
