### ISSUE TITLE
[BUG] Skeletons AI are bugged round start at the sewers

### ISSUE THREAD

**Issue by wgtjunior743** [Blackstone-SS13/BLACKSTONE#1119]
## Describe the bug

the title

## Round ID:

Tower482-01.13.10

## Steps to Reproduce:

It seems to have happened  last round too, they start at the ground unconscious, not dead but just there they also drop their weapons:
![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/47699733/45a15029-0289-4794-a814-8a606ed6d4e4)

![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/47699733/b8efabc1-4bf5-4890-8e0b-c50099ef461f)

## Additional context

I think it maybe was the zombie PR but i don't think that code touches the skeletons so i have no idea.

**Comment by CVSthePharmacy** [comment]
you're a meta rusher, fuck you

**Comment by wgtjunior743** [comment]
> you're a meta rusher, fuck you

https://tenor.com/view/ice-eating-ice-eating-meme-ok-gif-22520091

**Comment by wgtjunior743** [comment]
The skeletons are back to normal
