### ISSUE TITLE
[BUG] Bandit Disguises do not work

### ISSUE THREAD

**Issue by atomicplan666** [Blackstone-SS13/BLACKSTONE#1210]
## Steps to Reproduce: 

1. Become a Bandit 
2. Wear any disguise i.e hood, mask, etc 
3. Examine yourself 
4. Note that the "BANDIT" text still appears

## Additional context

Prevents bandits from sneaking into town, everyone just murders on sight. 

![image2png](https://github.com/Blackstone-SS13/BLACKSTONE/assets/50342682/2aa9adc0-c2f4-4e52-b8f2-a0592bc1f1d2)

![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/50342682/e25adb23-4828-4bfc-96de-0b21b0a62977)

**Comment by BlueMemesauce** [comment]
thats just cause youre examining yourself

**Comment by MickDick1** [comment]
Confirming this. Actually, the title should be "all disguises do not work".

You can wear a mask and all that as a town role like blacksmith or soiler etc and the examine is still outputting their job and race.

"unknown" the returning humen blacksmith, etc. Someone screwed it up.

**Comment by ChungusGamer666** [comment]
seems to be fixed
