### ISSUE TITLE
[BUG] Drow autocorrect too strong

### ISSUE THREAD

**Issue by Hmeister-real** [Blackstone-SS13/BLACKSTONE#1222]
## Describe the bug

 When you say Drown, Drowsy etc, it translates to "dark elfn" and "dark elfsy"

## Round ID:

all

## Steps to Reproduce:

Say drowsy or drown

## Additional context

h

**Comment by Hmeister-real** [comment]
issue 69!!!

**Comment by CVSthePharmacy** [comment]
dark elfsy??????????

**Comment by Real-MAGNUM** [comment]
I dont care if dark elf is synonymous with drow, could honestly kill the autocorrect entirely imo.

**Comment by pismorizzo** [comment]
Also major issue with no being non, a fuck load of words use NO and it messes them up constantly.

Nonrth
Knonwledge 
Unknonwn
I can go on but you get the idea

**Comment by Hmeister-real** [comment]
not my first issue, unless you mean my arrow issue was shit :(

**Comment by BlueMemesauce** [comment]
> Also major issue with no being non, a fuck load of words use NO and it messes them up constantly.
> 
> Nonrth Knonwledge Unknonwn I can go on but you get the idea

this is peak though

**Comment by monad76** [comment]
@Real-MAGNUM
So is deleting the line that autocorrects for drow enough to close the issue?

**Comment by WindowTalents** [comment]
I have no idea what is wrong with saying 'drow' other than that word *BEING OWNED* by Wizards of the Coast - for DND.

Do we care about that kinda shit... on SS13 lol? I alternate between saying 'drow' and 'dark elf' whenever I feel like it, never liked this ONE filter change... and I love the auto-corrects we have, they crack me up.

You jokers made me love the word nimrod so much, god damnit lol.

**Comment by BlueMemesauce** [comment]
Just because a word is owned doesnt mean you have to ban people from saying it? It's not like we're calling our game Drowstone or something whats the issue
