### ISSUE TITLE
[BUG] Bandit forces human

### ISSUE THREAD

**Issue by pismorizzo** [Blackstone-SS13/BLACKSTONE#1226]
## Describe the bug
Bandit changes your race to human

## Round ID:
Always done this.

## Steps to Reproduce:
Play Bandit as a non human race.

## Additional context
You keep your appearance so it’s not instantly obvious but you don’t get any stat changes, any accents and when examined it says you are a human.
I assume this is not intended but if for some reason bandits are forced human but keep their appearances let me know.

**Comment by CVSthePharmacy** [comment]
I played a tiefling and got made into a human

**Comment by MickDick1** [comment]
The code for bandit forces you to be humen.
This is clearly intentional. Why it's like this is a mystery, as it was always set up this way, so I guess Zeth determined they're monoracial.
