### ISSUE TITLE
[REQUEST] Add diagnose spell to court physician and towner doctors, make it be free cost

### ISSUE THREAD

**Issue by ophaq** [Blackstone-SS13/BLACKSTONE#1305]
Honestly it is pretty ass playing these roles when you have to diagnose a patient without the diagnose spell all in under a minute before they fucking bleed out to death and you have to use up all your sutures or some cleric comes by and does your job for you. At least make them useful in the moment to know where to heal and not just a backup/dead body healer. Examining every single body part or waiting for the player to say where they are hurt, if they are able to just makes these roles a slog and half the time I'm not even using my doctor tools because I'm too busy feeding these idiots water and using all my sutures or asking where the big boo boo is before priest mchealer jumps in and oingo boingos my boy with his healing spells. Free cost on diagnose because you are examining the patient and it won't work too well otherwise without giving these roles the cleric prayer function.

**Comment by Hmeister-real** [comment]
I think inspecting someone should automatically check every available limb, exactly how right clicking your health heart does it, except you don't see wounds hidden by clothes. Maybe it could be, like "the (clothing) is stained with a growing pool of blood" or "the (section of body) is covered, but you can feel blood under the (clothing)", which should be replaced with just "Covered by (armor)" if theres armor over the clothing

**Comment by WindowTalents** [comment]
If DIAGNOSE is basically "examine the player for injuries that I must fix" then yes, absolutely? Of course they should get it as a free spell with just a cooldown instead? That spell should, just be a function of the game, what?

I don't know how to add that though, if you can do it - do it!

**Comment by ChungusGamer666** [comment]
someone did it so
