### ISSUE TITLE
[REQUEST] MAKE THE VAULT HARDER TO GET INTO LOL

### ISSUE THREAD

**Issue by WindowTalents** [Blackstone-SS13/BLACKSTONE#1322]
## Is your feature request related to a problem? Please describe. 
I think I am seeing "the vault was robbed" every single round now.

## Describe the solution you'd like

A cooler vault, or just make the fucking shit harder to get into lol.
## Describe alternatives you've considered

The door locks automatically after a bit of time, and is MADE INDESTRUCTIBLE or FAR HARDER TO BREAK. The VAULT itself has entirely indestructible walls. Idk, who cares. Seriously, that shit is a single wooden door lol.
## Additional context

I think it is very funny that people give Worsen shit (it is NOT JUST THEM, I DO IT TOO) for breaking into the vault whenever they feel like it, when that is *quite literally* them pointing out that such a massively important thing can be broken into with such ease lol.

This is TECHNICALLY still SS13 - that shit SHOULD BE HARDER TO GET INTO WE GOTTA FIX IT LOL.

Try getting some moondust as, literally anybody, and just simply mine from the moat into the crypt and then smash the vault door in less than five minutes.

**Comment by Real-MAGNUM** [comment]
k will do
