### ISSUE TITLE
Concerning the Gatemaster

### ISSUE THREAD

**Issue by YosemiteYam** [Blackstone-SS13/BLACKSTONE#137]
Currently the gatemaster has become the most immobile and boring role to play ingame, mainly due the to the map's position on where to have the gates and pit. Beforehand the gates led into the town which led to interesting interactions and had the gatemaster play a vital role in the execution of the kings decrees concerning who to let into town. Now, the gatemasters are just a doorman who let people in and out of the keep for 3 hours which is incredibly dull, while buffing the keep too hard when it comes to rebellions/attacks due to the pit being there.

At the same time the gatemasters, which were envisioned as the serjeant/crossbowman role since you're supposed to be able to shoot through the bars or over the palisade walls at attackers, were nerfed in loadout and skill to be a 1-1 copy of a townwatchman, complete with a cudgel and skilled swordfighting skill, and no sword. With average crossbowman skill and thus unable to shoot anything.

I propose to fix these problems that the gates be moved to the western bridge to town and be made the only entry into town again, while fixing the gatemaster skill and gear to be more akin to a crossbowman man-at-arms rather than a town watchman, so this isn't literally a role made with zero chance for creativity.

**Comment by Cdey78** [comment]
Part of this is a map design issue with a specific map (RT2), though I'd like to come around to this with every role in mind. As it stands, every role is in a weird place due to missing or esoteric mechanics -- Guards will likely come last, but it would be nice to change the mechanics for them all.

A.K.A, pending proper design document.
