### ISSUE TITLE
character preview prevents seeing/editing character creation editor (see screenshots)

### ISSUE THREAD

**Issue by DeerJesus** [Blackstone-SS13/BLACKSTONE#14]
![wjhatisee](https://github.com/Blackstone-SS13/BLACKSTONE/assets/11761309/1b1f59c8-6095-4e9c-97de-6f002bfecf10)
not just happening to me, someone else reported it

both on version 514

**Comment by Reishi42** [comment]
Hello. Try delete folder BYOND from "My Documents". This will help you temporarily, but globally it needs to be fixed on the build side. This is mainly due to the fact that you log on to other servers besides RogueTown

**Comment by Cdey78** [comment]
The issue hasn't been solved yet, however, for anyone in the future suffering from this issue, please follow these steps;
) Disconnect from the server.
) Connect to Colonial Marines, it's typically at the top of the HuB or near such.
) Once the lobby loads, disconnect and reconnect to Blackstone.

If anyone finds a way to break it again after fixing it in this fashion, please let us know. So far it stays fixed (even on local hosts) after doing this.

**Comment by emoats18** [comment]
This has been fixed by JTGSZ thanks for the report!
