### ISSUE TITLE
Archivist May need another pass

### ISSUE THREAD

**Issue by Jakers457** [Blackstone-SS13/BLACKSTONE#15]
The travels seem to broken when going back to the Mansion
Doesn't seem to be a place for the Archivist to use his key
Most of the stuff doesn't appear to have a function within the Mansion.

**Comment by Jakers457** [comment]
![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/53007942/1961437b-ad7c-4a24-9b6d-bf99c59f84a4)

**Comment by Derrick2Electricboogaloo** [comment]
Agree, the job does literally nothing from my experience.
