### ISSUE TITLE
Armour cannot be repaired past %

### ISSUE THREAD

**Issue by wow50000** [Blackstone-SS13/BLACKSTONE#176]
some armours cannot be repaired for some reason, i was hitting a full plate malle with a hammer and it would not be repaired past 49% and half plate cannot be repaired past 79% for some reason

**Comment by wow50000** [comment]
![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/48336887/b1f5198b-dbcd-4834-aca8-6af436c550cf)
turns out repairing armour can lower the durability

**Comment by Cdey78** [comment]
Repairs are a skillcheck. Low skill smiths will fail to repair and damage the item further. Re-post if this isn't the issue you're having, please.
