### ISSUE TITLE
Shrunken Lanterns Give Off Weak Light

### ISSUE THREAD

**Issue by NGGJamie** [Blackstone-SS13/BLACKSTONE#178]
With the new lighting, shrunken lanterns only give off very weak light, making it hard to see for spirits. Needs to be adjusted up.

![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/6971628/610b7eee-0558-4ad4-b240-97a1f5a82125)

**Comment by LudwigVonChesterfield** [comment]
#177 ?

**Comment by Contrabang** [comment]
Fixed by #177
