### ISSUE TITLE
Issues with the new overlay lighting system 

### ISSUE THREAD

**Issue by BlueMemesauce** [Blackstone-SS13/BLACKSTONE#191]
#175 

Elves night vision now have infinite range in the dark, when previously the see_in_dark var allowed them to have night vision only up to 4 tiles

Your character can now see everything even if it supposed to be dark, since it's just an overlay. For example if someone does something in the dark that's a visible_message, your character will still technically see it and it will be in chat

You can still examine everything that's in the dark or hover your mouse over it to see what's there. This isn't that much of a problem since we disabled right click menu so you can't see everything that's on the tile, but humans generally take up the whole tile so you can still examine them easily

**Comment by Wintermote** [comment]
I can't even see 10 feet in front of me as a dark elf (no darkvision?)

I don't know if people have their gamma cranked up or I'm just missing some setting, but I wouldn't mind higher contrast between lit areas and dark areas. Right now it's a very muddy dark everywhere and things I should be able to see are actually very difficult to see and I'm almost practically squinting at my screen 24/7.

Moving through the forest at night as a bandit is basically impossible for example. I had to just give up on playing that. Yet there were other bandit players whizzing around in pitch darkness like it was nothing.

**Comment by BlueMemesauce** [comment]
We also need to double all the range of stuff #178 applies to all lights but we only fixed it for lanterns
