### ISSUE TITLE
Unable to withdraw from SHYLOCK

### ISSUE THREAD

**Issue by awpenh** [Blackstone-SS13/BLACKSTONE#194]
Issue reported from Blackstone (Rougetown on a Dedicated Server)

Reporting client version: 514.1589

Unable to withdraw any money of any kind from SHYLOCKS, account balance decreases but no money comes out with enough in the treasury to support it
players reporting similar but only with some denominations of currency

**Comment by wow50000** [comment]
yeah i couldnt get any gold coins from it and it would count as removing coins

**Comment by efzapa** [comment]
afaik withdrawing works, just broken with single coins of any type, eats the balance and gives you nothing
