### ISSUE TITLE
Introducing a Skill Progression Mechanic.

### ISSUE THREAD

**Issue by EnzoSeptum** [Blackstone-SS13/BLACKSTONE#216]
I was thinking about something that would add depth and immersion for the players (and actual character development).
Specifically, I suggest the possibility for characters to gradually enhance skills such as Climbing, Jumping, Sneaking, Stealing, Athletics, and etc... overtime.

Here's a breakdown of how it could work:

**Skill Progression:** Characters would have the opportunity to improve these skills through regular practice and/or dedicated training. The progression would be gradual to maintain balance in the game.
**Training Mechanism:** Players could enhance their skills by doing relevant actions repetitively overtime. For example, regularly practicing climbing to improve the climbing skill.
**Teaching Mechanism:** For skills not initially available to characters (ex. Steal for a Warrior class), a "Teach" verb could be implemented. This would require characters to seek out for other players who possess the desired skill and learn from them.
**Integration with Existing Systems:** Considering we already have an experience system for other skills like farming, integrating this skill progression mechanic should be possible.
I believe this addition would for real enhance the experience of blackstone, allowing for more diverse character development and interactions.

**Comment by TopHatPenguin** [comment]
we have a big issue atm of people just training their desired combat skill to legendary. Being able to also skill train would be another issue piled on top imho.

**Comment by EnzoSeptum** [comment]
> we have a big issue atm of people just training their desired combat skill to legendary. Being able to also skill train would be another issue piled on top imho. If it was exceptionally slow or hard limited to a point that may be better?

By setting hard limits, players can only upgrade 1-2 categories above their base skill level. For example if you have basic knowledge at wrestling, with training, your potential is being skilled at wrestling. For a rogue who is a master at sneaking he could become lengedary. 
I order to overcome these limits we could make use of the teaching mechanism that a previously mentioned (the "teach" verb) who you can only use once per player. Let's use the other example of wrestling, you'd need multiple who are skilled at wrestling or a master at wrestling to share knowledge with you via teaching to be able to overcome your plateau . If you didn't have the skill and learned it from someone you shouldn't be able to make use of the teach mechanic again for this.  That way, it would prevent a Paladin with legendary stealing for example. Or a orphan with legendary fist fighting.

**Comment by Wintermote** [comment]
Honestly I don't like that skills can be improved during the game. It's a bit tedious to do every single round, too. 

I do like that it can give you a bit more character flavor, but honestly I'd rather that be in the character creator rather than spending 30 minutes in game to train something up.

I think what I'd rather see is a a soft cap on training (like, you can only train +1 level above what you start with) but when making your character you can select a couple skills to boost up a level or two.

So for example, you might normally start with a skill at level 3, trainable to level 4 in-game, but you chose that skill as a major skill, so it starts at level 4 and is trainable to level 5 now.

**Comment by EnzoSeptum** [comment]
> Honestly I don't like that skills can be improved during the game. It's a bit tedious to do every single round, too.
> I do like that it can give you a bit more character flavor, but honestly I'd rather that be in the character creator rather than spending 30 minutes in game to train something up.

It is your decision either you train or not, is not like anyone is forcing you. The game would still be the same. 

> I think what I'd rather see is a a soft cap on training (like, you can only train +1 level above what you start with) but when making your character you can select a couple skills to boost up a level or two.
> So for example, you might normally start with a skill at level 3, trainable to level 4 in-game, but you chose that skill as a major skill, so it starts at level 4 and is trainable to level 5 now.

Read my answer to TopHatPenguin that is above your comment.

**Comment by YosemiteYam** [comment]
> > Honestly I don't like that skills can be improved during the game. It's a bit tedious to do every single round, too.
> > I do like that it can give you a bit more character flavor, but honestly I'd rather that be in the character creator rather than spending 30 minutes in game to train something up.
> 
> It is your decision either you train or not, is not like anyone is forcing you. The game would still be the same.

It does kind of force you when mechanically you are at a complete disadvantage when most of the server is at master/legendary skill and can all of your attacks. Training is borked, the real issue should be "Training needs to be capped at Skilled so every round isn't an anime montage of training for more than half the playerbase". Not even more skill progression mechanics that are harder to implement than a simple cap.

**Comment by EnzoSeptum** [comment]
> By setting hard limits, players could only upgrade 1-2 categories above their base skill level. For example if you have basic knowledge at wrestling, with training, your potential is being skilled at wrestling. For a rogue who is a master at sneaking he could become lengedary.
> In order to overcome these limits we could make use of the teaching mechanism that I previously mentioned (the "teach" verb) which you can only use once per player. Let's use the other example of wrestling, you'd need multiple who are skilled at wrestling or a master at wrestling to share knowledge with you via teaching to be able to overcome your plateau . If you didn't have the skill and learned it from someone you shouldn't be able to make use of the teach mechanic again for this. That way, it would prevent a Paladin with legendary stealing for example. Or a orphan with legendary fist fighting.

Setting hard limits, players could only upgrade 1-2 categories above their base skill level. For example if you have basic knowledge at wrestling, with training, your potential is being skilled at wrestling. For a rogue who is a master at sneaking he could become lengedary.
In order to overcome these limits we could make use of the teaching mechanism that I previously mentioned (the "teach" verb) which you can only use once per player. Let's use the other example of wrestling, you'd need multiple who are skilled at wrestling or a master at wrestling to share knowledge with you via teaching to be able to overcome your plateau . If you didn't have the skill and learned it from someone you shouldn't be able to make use of the teach mechanic again for this. That way, it would prevent a Paladin with legendary stealing for example. Or a orphan with legendary fist fighting.

**Comment by EnzoSeptum** [comment]
> > > Honestly I don't like that skills can be improved during the game. It's a bit tedious to do every single round, too.
> > > I do like that it can give you a bit more character flavor, but honestly I'd rather that be in the character creator rather than spending 30 minutes in game to train something up.
> > 
> > 
> > It is your decision either you train or not, is not like anyone is forcing you. The game would still be the same.
> 
> It does kind of force you when mechanically you are at a complete disadvantage when most of the server is at master/legendary skill and can parry all of your attacks with just standing there. Training is borked, the real issue should be "Training needs to be capped at Skilled so every round isn't an anime montage of training for more than half the playerbase". Not even more skill progression mechanics that are harder to implement than a simple cap.

Read all them comments please, imma copy paste it again
