### ISSUE TITLE
Adding a lot of spawn points and removing the spawncamp rule

### ISSUE THREAD

**Issue by EnzoSeptum** [Blackstone-SS13/BLACKSTONE#218]
I've noticed that the current spawncamping rules could really cause some ambiguity and potential unfairness due to the lack of clearly defined spawn zones. This can lead to confusion, unfair bans, and a flood of ahelptickets.

Now, being honest, having delimited spawn zones would make things much more artificial.

By adding numerous spawn points across the map, it could reduce for real the likelihood of spawncamping. With players spawning from various locations, it becomes much more challenging for people to wait and target specific spawn points. 

And instead of relying solely on a spawncamping rule, we could implement a system where players are temporarily invulnerable after spawning, lasting for around 30 seconds or 1 minute. This grace period would prevent players from being caught off guard immediately after spawning, allowing them to orient themselves and lock in the game without fear of immediatially getting attacked.

**Comment by Cdey78** [comment]
I'll possibly look into just not spawning people near other people when applicable, And/or a warning if players are nearby when you spawn.

**Comment by Osmos123** [comment]
#302 
This should help with the spawn camping (at the very least prevent a rogue from oneshotting you with a crossbow). Should be expected for you to run straight into the map than laying around the spawn zone.

**Comment by NGGJamie** [comment]
I'm going to call #302 as being the resolving PR unless new issues come out of it.
