### ISSUE TITLE
Graveyard should probably have gates

### ISSUE THREAD

**Issue by Gyrandola** [Blackstone-SS13/BLACKSTONE#231]
Old map graveyard had gates that were only openeable with the crypt key. On this new map it is a total unmanageable mess, it is near impossible to give a body proper rites when there's swarms of beggars looting the corpses you are trying to dig a grave for, thus it also prevents gravediggers from taking their toll and earn a living.

**Comment by Scarlet-Oduko** [comment]
gates have been added in the recent remodel of it, haven't gotten too much feedback though so let me know if I missed something.

**Comment by Gyrandola** [comment]
> gates have been added in the recent remodel of it, haven't gotten too much feedback though so let me know if I missed something.

I think it's good now!
