### ISSUE TITLE
Gatekeeper loadout

### ISSUE THREAD

**Issue by YosemiteYam** [Blackstone-SS13/BLACKSTONE#24]
Gatekeepers crossbow spawns with arrows not bolts, combined with the fact that gatekeeper doesnt start with any weapon either so the serjeant of the town guard is basically defenseless 

Also not sure if its randomized but gatemaster appears to have master skill in archery and expert in crossbows, should probably be switched around

**Comment by emoats18** [comment]
I have given the gatekeeper a sword hopefully that is good enough if needed I will change the loadout more thanks for the report!
