### ISSUE TITLE
No archives

### ISSUE THREAD

**Issue by DirtTastesBad** [Blackstone-SS13/BLACKSTONE#263]
Unless it's just in a super niche location that no one knows about, there is no proper archives. There's the library by the lord's room in the upstairs of the keep, but imagine that's not the intended archives given that there's nothing in there but a bunch of empty bookshelves with books painted onto their sprite, and that the archives key doesn't even work on the door.

**Comment by Real-MAGNUM** [comment]
Believe it or not, there are books in there. They're all TG books unfortunately, and the bookshelves cant be looked into for god knows why.
