### ISSUE TITLE
Burying people frees open a slot

### ISSUE THREAD

**Issue by Osmos123** [Blackstone-SS13/BLACKSTONE#267]
Not sure if its intended or not, but I've seen the adventurer slots fluctuate between 74 and 75 and I have been able to join as adventurer late into the game. I could be completely wrong, maybe another factor changing it.

**Comment by Gyrandola** [comment]
Isn't that good?

**Comment by BlueMemesauce** [comment]
Seems like it's working as intended

**Comment by Wintermote** [comment]
I think this was intentional

**Comment by Osmos123** [comment]
I guess I am looking at the possible cheese that can be done with this as most important/powerful roles are now late joinable. Knights are latejoinable (usually filled) so burying one can allow you to get another with its skills/armor.

**Comment by NGGJamie** [comment]
Adventurer specifically limits based upon how many are currently alive, it is a unique feature to their role.
