### ISSUE TITLE
Bank Accounts Issue (they aren't unique)

### ISSUE THREAD

**Issue by Kush1Push1** [Blackstone-SS13/BLACKSTONE#270]
During creation of a bank account, the game uses the real name of a mob.

If two people have the same name, they do have the same account.

Many people have 1-worded names from pre-generated list, so on accasion, adventurers can found out they have some belongings on their bank accounts.

![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/78963858/c8acb231-3391-4c74-9530-365d65aa7468)

**Comment by Kush1Push1** [comment]
As a paladin with pre-generated name, for an example, I did withdraw of 180 mammons of some poor (now actually poor lol) man and donated 'em to the church.

**Comment by NGGJamie** [comment]
Will be fixed in #305
