### ISSUE TITLE
cant repair gorgets

### ISSUE THREAD

**Issue by wow50000** [Blackstone-SS13/BLACKSTONE#284]
yeah

**Comment by wow50000** [comment]
seems some other clothes cant be repaired with a needle on a table including but not limited to, 0% gambesons and boots

**Comment by wow50000** [comment]
buckled hats and chain coifs at 0% also

**Comment by YosemiteYam** [comment]
You're not supposed to be able to repair 0% items I'm pretty sure? They're considered completely broken

**Comment by wow50000** [comment]
i know that but its not giving me the "x hits item with hammer" either or letting me put these items on an anvil

**Comment by wow50000** [comment]
whereas if i did it with a repairable item it would give me that message
