### ISSUE TITLE
Sheriff can be turned into a plotter/rebel

### ISSUE THREAD

**Issue by thekillerchef** [Blackstone-SS13/BLACKSTONE#298]
Issue reported from  Round ID: 39 (Blackstone (Rougetown on a Dedicated Server))

Reporting client version: 514.1589

got sheriff and had the objective to be crowned as monarch, and got an ability to recruit guardsmen, but it dosen't work just says "there are no potential recruits in range" even when there are.

**Comment by ChungusGamer666** [comment]
Pretty sure that the recruit ability works fine as it is the same system as bog master's recruit spell, and that one works fine.

**Comment by Cdey78** [comment]
Sheriff isn't supposed to be a plotter/rebel, keep this open

**Comment by Osmos123** [comment]
Yep similiar thing, rolled as Sheriff and got this 
![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/126647931/a57be093-2017-4020-89a5-16fff698df33)

**Comment by Autisem** [comment]
From the code this actuely seems intentional. I think the idea is that these are noble positions and they think the king is stupid

**Comment by YosemiteYam** [comment]
I think they always get those objectives though, every time I've rolled sheriff I've always had that as an objective

**Comment by ChungusGamer666** [comment]
Not a bug, sheriffs are a separate ""antagonist"" called aspirant which gets applied to noble positions... It is quite weird.
