### ISSUE TITLE
[BUG] When a Cleric is made an Acolyte of the Church, their spells double

### ISSUE THREAD

**Issue by Wintermote** [Blackstone-SS13/BLACKSTONE#315]
As a cleric, if the priest turns you into an acolyte of the church, you will be granted a new set of spells according to your patron diety, in effect doubling up all your spells. (e.g. 2 lesser miracle).

These spells all work independently, so you really can cast lesser miracle twice in quick succession.

## Round ID:
Happens in every round (and I can't copy paste the round ID's)

## Steps to Reproduce:
1. Play cleric
2. Have the Priest make you an acolyte
3. You now have 2x the spells

**Comment by ChungusGamer666** [comment]
oh that is really god damn funny lol

**Comment by ChungusGamer666** [comment]
working on this

**Comment by ChungusGamer666** [comment]
fixed by commit 7518311c4101611451856602fbc3780569d88590
