### ISSUE TITLE
[BUG] cant repair items as smith

### ISSUE THREAD

**Issue by wow50000** [Blackstone-SS13/BLACKSTONE#320]
cant repair items

when i try to hammer damaged items it does not say i repaired it or hit it with the hammer, its like it doesnt recognise it is hammerable
## Steps to Reproduce:try to repair items

i am a smith main i know how to play smith

**Comment by Xander3359** [comment]
Is the item at 0% Durability?
0% Durability items cannot be repaired.

**Comment by wow50000** [comment]
no, hunting knife, 60%

**Comment by wow50000** [comment]
i main smith and nothing is repairable rn
i think the new "balance" pr fucked it
