### ISSUE TITLE
[REQUEST] Bind numpad back to body targeting

### ISSUE THREAD

**Issue by OzfurAtlas** [Blackstone-SS13/BLACKSTONE#367]
Why does TG have this but we dont?

**Comment by Wintermote** [comment]
I don't think I'd use it anyway, shift+scrollwheel goes through all the selections

Only improvement here I can think of is something like shift+scrollwheel selects main body parts (head, body, l/r/ arm/leg) and shift+ctrl+scrollwheel does specific parts of what's selected

**Comment by Wozzy09** [comment]
why tg have and dont? bc we dont casuals, only hardcore
