### ISSUE TITLE
Necklace sprite is invisible

### ISSUE THREAD

**Issue by Hmeister-real** [Blackstone-SS13/BLACKSTONE#42]
I forget which class, but and adventurer class spawns with an invisible stock "Necklace" with no sprite

**Comment by AMyriad** [comment]
this one's tricky to find
is the item just called "necklace"?
can ye recall anything else about the class, or remember what it's called?

**Comment by Hmeister-real** [comment]
> this one's tricky to find is the item just called "necklace"? can ye recall anything else about the class, or remember what it's called?

Yes, monk starts with it round start on their neck
