### ISSUE TITLE
[REQUEST] Templar Amulet

### ISSUE THREAD

**Issue by wgtjunior743** [Blackstone-SS13/BLACKSTONE#422]
Issue reported from  Round ID: 110 (Blackstone (Rougetown on a Dedicated Server))

Reporting client version: 515.1633

As a templar it seems no matter what god you pick, you will start with Astrata amulet, for example i picked Pestra and had Astrata amulet, please make so each patron start with their own amulet as they are already ingame.
![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/47699733/8534d73b-c19e-4909-b595-ec0277ea5e74)

**Comment by ChungusGamer666** [comment]
Gonna fix it

**Comment by ChungusGamer666** [comment]
fixed
