### ISSUE TITLE
[BUG] Vault room not registering items of value

### ISSUE THREAD

**Issue by Yellows91** [Blackstone-SS13/BLACKSTONE#436]
## When you put something in the vault room its suppose to register it as a 'treasure' which gives interest. However it doesn't seem to be working as when you put something such as a gold statue in there. It doesn't count it as a 'treasure' no matter where it is in the room.

When you put 'treasure' in room, it is counted as 'hoarded gold' and will give mammon interest per what the tax rate is.
## Additional context.
Im not really sure whats happening but It doesn't seem to want to work with gold statues or items with value that is placed within the room.

**Comment by Yellows91** [comment]
Tried this again on round Weed-121-02.0.4.22. In a crate, out of crate, on E, out of E and isn't registering on the nerve center as 'accumulated treasure'

**Comment by NGGJamie** [comment]
May have been fixed by #544 ?

**Comment by Yellows91** [comment]
Most likely fixed by #544
