### ISSUE TITLE
[REQUEST] Increase the storage capacity of satchels

### ISSUE THREAD

**Issue by Wintermote** [Blackstone-SS13/BLACKSTONE#445]
## Is your feature request related to a problem? Please describe. 
Storage capacity is extremely limited in its present state, with combat roles often only being able to carry 3-6 items, of which most end up being necessities like medical and survival/utility gear (knife/needle/cloth). However even playing in non-combat roles, making (or starting with) a backpack almost feels mandatory to have any useful storage space.

Storage constraints are, imo, a good thing, but in the present state it leans too far on constraining players.

The current storage capacities are:
Belt - 3 slot, 6 weight [Limit - Small/Tiny]
Pouch - 3 slot, 6 weight [Limit - Normal]
Satchel - 3 slot, 21 weight [Limit - Normal]
Backpack - 14 slot, 42 weight [Limit - Normal]

Item weight is defined as (? not sure on this):

> WEIGHT_CLASS_TINY     1 //Usually items smaller then a human hand, (e.g. playing cards, lighter, scalpel, coins/holochips)
> WEIGHT_CLASS_SMALL    2 //Pockets can hold small and tiny items, (e.g. flashlight, multitool, grenades, GPS device)
> WEIGHT_CLASS_NORMAL   3 //Standard backpacks can carry tiny, small & normal items, (e.g. fire extinguisher, stun baton, gas mask, metal sheets)
> WEIGHT_CLASS_BULKY    4 //Items that can be weilded or equipped but not stored in an inventory, (e.g. defibrillator, backpack, space suits)
> WEIGHT_CLASS_HUGE     5 //Usually represents objects that require two hands to operate, (e.g. shotgun, two-handed melee weapons)
> WEIGHT_CLASS_GIGANTIC 6 //Essentially means it cannot be picked up or placed in an inventory, (e.g. mech parts, safe)

e.g. I'm pretty sure it means a pouch can hold 3 small, or 1 normal 1 small and 1 tiny, or 2 normal 

It may also be worth (though a little out of scope) rebalancing armor weight classes; at present most of them seem to be WEIGHT_CLASS_NORMAL (although I cannot actually find their weight class defined anywhere) instead of (imo more appropriately) WEIGHT_CLASS_BULKY; such a change should necessitate increasing the backpack weight limit to bulky from normal so people can still pick and store armor they find in backpacks, but not the other storage options. 

Currently I know a satchel can fit a steel half-plate as I've stored them in my satchel before. According to the code above, a pouch that you can wear around your neck, should also be able to fit 2 steel half plate in it, which I don't think it should.

## Describe the solution you'd like
Increasing the slot capacity of satchels to 7 so they are half a backpack instead of less than 1/4th of a backpack
(I don't think satchels need adjusting to their numerical weight limit (21), but that may prove otherwise with playtesting)

All roles would thus see a storage capacity increase of between 4 and 8 slots, depending on whether they carry 1 or 2 satchels, but no weight limit increase.

Maximum storage capacity would then be 33 slots using 1 backpack, 1 satchel, 3 pouches, 1 belt; up 4 from 29 currently.

## Additional context
I think this is inevitably going to happen anyway, I haven't talked to a single person yet who thought the current storage capacity of satchels was in a good spot, though I'm sure someone prefers how things are now and doesn't want to see it changed.

Mostly I want to get feedback on appropriate values; I think anywhere between 5 and 7 puts satchels into a good spot. I lean towards 7 because it provides useful space for those with 1 satchel to store items besides basic utility stuff.

Utility items I imagine will also be further increased over time (e.g. bedrolls ?, non-perishable food ?); it's easy to see how fast a few small interesting additions could easily happen down the line and would eat up available storage. Even this current proposed change might need further increasing down the line.

**Comment by OrbitalParadise** [comment]
Idk if you knew this but If you put a pouch in a satchel slot you can increase your storage capacity, putting an additional pouch around your neck increases it by 3, wearing a cloak of any kind increases it by 1. Also keyring can be put on the arm brace slot. 

Let's sum it up, 3 from the satchel pouch, 2 slots left in the satchel, 3 from the neck pouch,
1 cloak slot, 3 belt slots, 2 storage belt slots

A player can have the maximum of 14 storage slots already with how things are. Holding 2 things in your hand increases it to 16. This is all only using 1 satchel.

You can also put pouches on your storage belt slots. 

And further increase your storage even more by putting more pouches in your satchel. If you increase satchels by 7 it would be so so so so much.

**Comment by Wintermote** [comment]
I'm aware of it, I just don't think it's an issue.

Frankly, nested storage is aids. When you've got more than one pouch you have no idea which ones store what items, you have to pull pouches out individually to check what's in them like it's a backpack, now defeating the entire benefit of using a satchel, and this nested storage can be used to much greater effect with a backpack which you don't seem to have any issue with for some reason.

I think if it really is such a problem then we can try:
1. Disabling nesting pouches inside satchels/backpacks
2. Reducing pouches to WEIGHT_CLASS_SMALL items rather than WEIGHT_CLASS_NORMAL
3. Limiting nested storage to 1 or 2 pouches rather than as many as you can stuff in 

The current nested storage functionality is something almost nobody uses, and the times I've seen it used, people are only storing 1 pouch, not 2 or 3 of them, despite that being possible.

Let me know what you think works as a way to solve this, because the current satchel capacity is absolute aids right now and just stuffing pouches into everything doesn't sound sane and isn't easy to use; basically defeats the entire point of using a satchel instead of a backpack.

**Comment by YosemiteYam** [comment]
You have more than enough storage space to carry necessities with satchel+belt+pouches. The only thing you're prevented to do is lug around abunch of large items/loot inside personal satchels (you can still do this with a backpack) which is realistic, it should be clunky and hard to move a bunch of armors, items etc without the use of something like a backpack with the eight slots or a cart. I only see this benefitting combat mains being able to loot and store a bunch of shit like armors/weapons inside their satchels which imho are supposed to be the size of laptop bags.

**Comment by ChungusGamer666** [comment]
Limited inventory space is nice, this issue only makes me want to nerf backpacks
