### ISSUE TITLE
[BUG] Being Derotted as a living zombie does not fix your stats 

### ISSUE THREAD

**Issue by pismorizzo** [Blackstone-SS13/BLACKSTONE#447]
## Describe the bug
When derotted as a living zombie your stats do not return to normal and your vision stays greyscale.

## Round ID:
Weed121-02,04,22

## Steps to Reproduce:
Die
Wait to become zombie
Have derot spell fix you, possibly need to be standing near the cross but unsure.
Vision remains greyscale and although human again your stats remain completely fucked at zombie levels.

## Additional context
Pretty bad bug, basically makes revival of someone who is a zombie pointless.

**Comment by UbaserB** [comment]
I have confirmed this bug ingame, the only thing that happens is that the gross miasma stuff from rotting goes away, i cant even tell what colour my skin is cause its all grey

**Comment by wgtjunior743** [comment]
I can also confirm this bug, yesterday we even had another that derotted people were getting burned to the miracle as they were still some type of undead.
Proof of my stats:
![statdissapeared](https://github.com/Blackstone-SS13/BLACKSTONE/assets/47699733/5f827f69-00ec-4893-8963-a672d45288a6)
And they really became like that 1 speed, not being able to hold my sword and other stuff from such 0 0 1 stats.

**Comment by ChungusGamer666** [comment]
I repeatedly tried to cause this bug yesterday and could not.

**Comment by wgtjunior743** [comment]
> I repeatedly tried to cause this bug yesterday and could not.

Strange, maybe someone fixed since when i did the admin report the admin said someone was working on it, i will try to repeat this bug today and ask some people that get unroted.
