### ISSUE TITLE
[BUG] Paladin God not matching selected god in Character Setup

### ISSUE THREAD

**Issue by MurdoofAstora** [Blackstone-SS13/BLACKSTONE#478]
## Describe the bug

When spawning in as a Paladin of Ravox, my Patron immediately changed to that of Necra.

## Round ID:

Sherax138-09.15.35

## Steps to Reproduce:

When creating a character, select a Patron that isn't Astrata, Necra, Pestra or Dendor. Join the game as an Adventurer, select Paladin.

## Additional context

This could perhaps be due to the fact that Ravox and by extension the other gods do not have any Miracles associated with them? Not sure.

**Comment by ChungusGamer666** [comment]
Ravox has no associated spells and is not an allowed patron of paladins. This is not a bug.
