### ISSUE TITLE
[REQUEST] Parrying arrows and bolts with a sword 

### ISSUE THREAD

**Issue by wow50000** [Blackstone-SS13/BLACKSTONE#509]
## Describe the solution you'd like

would be pretty funny if legendary swordsmen could parry arrows, it is possible irl but side stepping them at range is infinitely better

## Additional context

yeah i can see this getting rejected

**Comment by wow50000** [comment]
https://www.youtube.com/watch?v=6lYoMwXtpNA

**Comment by ChungusGamer666** [comment]
lol wtf no
