### ISSUE TITLE
[BUG] Someone check the damage of the Saiga animal

### ISSUE THREAD

**Issue by Osmos123** [Blackstone-SS13/BLACKSTONE#512]
## Describe the bug
Does a million-fucking damage. Broke me armor, did not even attack it.

**Comment by hivemuscle** [comment]
female saiga deals 10-25
rare male saiga deals 60-90
kid deals 1-6

![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/141878107/1a382df0-a2f3-418e-a37c-7934b4efeca5)

**Comment by CVSthePharmacy** [comment]
but how do you tame them then
