### ISSUE TITLE
Class Selection Window text formatting breaks when clicking Reset

### ISSUE THREAD

**Issue by Cementtt** [Blackstone-SS13/BLACKSTONE#52]
Once you click the reset button, all the text gets compressed in a way that is certainly not planned, some roles even dont show on the window unless you increase the size on the window.
![ClassSelectionWindowBug](https://github.com/Blackstone-SS13/BLACKSTONE/assets/166938348/3a4f61d2-88df-4189-9cf1-52739e6801de)

**Comment by emoats18** [comment]
Fixed by TH! Thanks for the report!
