### ISSUE TITLE
[REQUEST] Add caps to training skills depending on class

### ISSUE THREAD

**Issue by challade** [Blackstone-SS13/BLACKSTONE#521]
## Is your feature request related to a problem? Please describe. 
Yes. Everyone stands around for 1-2 hours training sword/maces to get to legendary so they can stand a chance in any fight that will last 3 minutes at most. It's frustrating to the player who trained, it slows down the interactions in game because everyone stands around training, and it removes the flavor of classes if any class can just get master on bows; it just makes classes solely a "what gear/stats can I start with." issue. This makes INT very overpowered, and it just has the bogmen training for 2 hours inside their fort while everything gets torn apart in the forest by RDMers.

## Describe the solution you'd like

Cap most skills to average, with specialized skills capped at master/expert/skilled. For example. A rogue can get master in daggers, skilled with crossbows, but average in most everything else, while an assassin gets legendary daggers, expert crossbow, skilled swordsmanship, etc. 
Sentinels get legendary bow, rangers are master bows, hunters expert, with a cascade of skills going down the totem pole, with Sents getting expert swordsmanship, rangers getting skilled, etc. 

However, Hunters might get Master leatherwork, while Sentinels and Rangers only get expert. See? It goes both ways. Peasants can get specialized skills like carpentry making them actually useful and desired by towners and adventurers alike. 

This way, if a master swordsman rolls into town, he can be actually intimidating with Legendary swords skills, while the other swordsmen are Expert at most. 
Guards get pikes at skilled, average most everywhere else and they'll have to rely on teamwork and their early game armored advantage rather than trying to solo specialized classes, adding flavor to interactions.
Monks can be absolute beasts with their fists and grappling instead of training weapons, having picked their class for the +3 STR. Mages get skilled polearms for their staff and a dagger skill, maybe, and that's it, buffing some of their CON and speed (that's dookie, likely because of them being able to speed run to master on everything whilst having spells).

## Describe alternatives you've considered

You could remove training altogether, but that also removes the atmosphere of trained fighters duking it out. As well as remove agency in builds. Maybe I want to be a ranger that carries a mace at average instead of a sword at skilled, maybe I like that playstyle better.
Also, you can consider giving elder characters an extra boost to training here or there, like an elder guard having either expert in pikes or gaining a skilled wrestling attribute.

## Additional context

Wouldn't it be better if the skills you start out with **actually** mattered and you didn't have to lament picking a pilgrim just because of the stats? And now you can be a chef because everyone is average at cooking and people want you for being an expert.
It could also add more flavor to races, for example, maybe elves get a skilled bowmanship cap (they have to train it still), and dwarves get skilled crossbowmanship cap as well as a higher cap on smith skills (better smiths). 
Humans are naturally better at wrestling maybe?Half elves get a random skill cap somewhere (they won't know until they train it).
Aasimars better at miracles, etc.
You could also lower caps depending if you get a lower INT. Like, a 6-8 int player has weak skill caps here or there.
Overall, talking about it on the discord, it's unanimously liked. No one likes spending 1-2 hours training, and no one likes that people are all training their stats constantly for a fight that lasts 3 minutes anyway.

**Comment by ChungusGamer666** [comment]
Alternative solution coming soon
