### ISSUE TITLE
[BUG] Necra's Burial Rites don't seem to be working

### ISSUE THREAD

**Issue by Eonoc** [Blackstone-SS13/BLACKSTONE#526]
## "Unknown Man whispers, "Undermaiden grant thee passage forth and spare the trials of the forgotten."
I failed to perform the rites."

**Comment by Wozzy09** [comment]
you put a mark on grave, you dont need it, thats why its failed

**Comment by Eonoc** [comment]
If you saw in my description, I both marked and unmarked graves. Neither worked.

**Comment by Wintermote** [comment]
It just feels completely random whether it works or not.

My hunch is that it only works if the person being buried is still occupying the corpse and hasn't gone to the underworld - the most recently deceased players are the ones I've anecdotally had the most success with doing rites and burying successfully.

Whether the grave has a marker or coin doesn't seem to matter at all for burial rites working.

**Comment by ChungusGamer666** [comment]
You marked the grave... I tested this myself, burial rites works fine.
