### ISSUE TITLE
[BUG] Inconsistent zombie dying

### ISSUE THREAD

**Issue by Osmos123** [Blackstone-SS13/BLACKSTONE#537]
## Describe the bug
I die to a skull crush from a mace as a zombie. I skull crush this player zombie and they are back up not caring about that. There is something very inconsistent.

**Comment by Gyrandola** [comment]
I wasn't able to kill a zombie by crushing their skull either.

**Comment by Hmeister-real** [comment]
Zombies can only die to beheading, crushing their skull does nothing but stun them really, the only non-killing moves that really harm them is de-limbing which can stop them from grabbing or walking. This is intentional

**Comment by ChungusGamer666** [comment]
Crushing their skull kills them but it does not last very long, they rise back up later
