### ISSUE TITLE
Undead being able to bite through parries

### ISSUE THREAD

**Issue by Viniwizi** [Blackstone-SS13/BLACKSTONE#541]
Undeads are being able to bite you multiple times during a fight, even if they only have a 1% chance of landing the bite.

I think this issue is exclusive to player undeads, but im not sure.
this makes fighting undeads the most dangerous thing in blackstone, since no matter how skilled you are with a blade, if they manage to land bites in your neck you will eventually bleed out.

**Comment by ChungusGamer666** [comment]
Not true. Checked the code, there is a parry check.

**Comment by Viniwizi** [comment]
> Not true. Checked the code, there is a parry check.

Thats the problem, it should not be bypassing it.
