### ISSUE TITLE
Rapier+Swift Crit Fishing

### ISSUE THREAD

**Issue by H0gberg** [Blackstone-SS13/BLACKSTONE#543]
## Is your feature request related to a problem? Please describe. 
Currently Crits are tied to one's intelligence score, while rapiers/sabers are able to attack extremely fast, this coupled with situations like a vampire lord having no stamina can lead to extremely fast crit fishing for eyes which can kill anyone almost instantly, regardless of skill level

## Describe the solution you'd like

A change to rapier's attack speed on swift, like maybe putting it on swift does nothing, furthermore possibly reducing the lethality of crits in the eyes and head will help to stop this issue. Additionally the removal of vampire's ability to abuse the lack of needing stamina would help future issues with vampires as well.

**Comment by panvxv** [comment]
Crits aren't tied to intelligence.
It is true fast attacks can land between parries but being on defend intent removes cooldown of parries and dodges.

**Comment by Hmeister-real** [comment]
now that you cant eye crit, this is mostly a non-issue?
