### ISSUE TITLE
[REQUEST] Bog Spawning 

### ISSUE THREAD

**Issue by OrbitalParadise** [Blackstone-SS13/BLACKSTONE#548]
## Is your feature request related to a problem? Please describe. 

Hate to say it but the slog from being spawned in bog to then go to town isnt fun, it would be better to have some adventerers/pilgrims spawn in the boat or even the tavern just for storytelling. Having it be the sole spawning grounds for half the server takes away the magic from the map and makes it more of a frustrating thing.

## Describe the solution you'd like

Idk bro

**Comment by BlueMemesauce** [comment]
Well roles like the bog guard have their entire purpose based around letting people into the town
