### ISSUE TITLE
[REQUEST] Zombie infection given more time

### ISSUE THREAD

**Issue by pismorizzo** [Blackstone-SS13/BLACKSTONE#549]
## Is your feature request related to a problem? Please describe. 
Zombies as it currently stand negate parries with bites meaning every bite is just a 7% chance to instakill any target after a VERY short amount of time, especially since they can just target unarmored areas like feet.

## Describe the solution you'd like
Increase the amount of time an infection takes to fester and make it more visible, most people I see infected drop dead BEFORE the fight is even over, basically no time to react much less run 2 minutes to the church and scream for a derotting. Most dont even know they have been infected as a single tiny "I dont feel good" doesnt take importance during a life or death battle.

## Describe alternatives you've considered
Additionally just make infection mean you zombify instantly AFTER death, or that bites dont negate parries entirely meaning a zombie cant just grab you and bite over and over on your unarmored foot with no downside. If 541 is just a bug and not intended fixing that will help this problem but not fix it entirely.
#541 

## Additional context
Trained warrior fights random rotting corpse who just walks up and nibbles his feet through his leather shoes, warrior drops dead in seconds is too common and has no counterplay.

**Comment by Wintermote** [comment]
Honestly I'd like to see a bump both in time for corpse to rot/zombie to 7-10 minutes, and time to turn zombie from infection to 5-7 minutes.

There's not much point in the spells we have for these things if people never even make it to the church in time.

Should also be a disclaimer when someone presses the 'journey to the underworld' button, that they're giving up their chance to be revived/become a zombie player by doing so.

**Comment by ChungusGamer666** [comment]
Zombies do not negate parries, this is misinformation
