### ISSUE TITLE
Lighting does not update correctly / fast enough

### ISSUE THREAD

**Issue by armorheart** [Blackstone-SS13/BLACKSTONE#57]
When walking with a dynamic lightsource, lighting does not update source fast enough to keep with player at times.
Movement continues, but lightsource lags behind for 2-5 seconds.

**Comment by JTGSZ** [comment]
This is tied to current performance issues outside of lighting, its ongoing work rn.

**Comment by LudwigVonChesterfield** [comment]
Closed? #82

**Comment by NGGJamie** [comment]
While #82 does help a lot to fix this issue, I don't think we can really call it resolved until we implement clientside lighting. During peak times, lighting can still be fairly slow.
