### ISSUE TITLE
[BUG] Commend Yes button not existing

### ISSUE THREAD

**Issue by wgtjunior743** [Blackstone-SS13/BLACKSTONE#607]
Issue reported from  Round ID: 213 (Blackstone (Rougetown on a Dedicated Server))

Reporting client version: 515.1637

I thought i was crazy but the YES button is not clickable and only the NO one.

![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/47699733/1a0e4f0b-cdee-475a-8c2d-5d67b9a3011b)

**Comment by BlueMemesauce** [comment]
trolled
