### ISSUE TITLE
[BUG] Endround OOC issue

### ISSUE THREAD

**Issue by Yellows91** [Blackstone-SS13/BLACKSTONE#624]
## Steps to Reproduce:
1.End round
2. Be alive
3. Attempt OOC verb while alive

**Comment by Wintermote** [comment]
You have to go to the ooc tab top right and then click the ooc button to talk

it's a pain

**Comment by Yellows91** [comment]
> You have to go to the ooc tab top right and then click the ooc button to talk
> 
> it's a pain

Thats what I am reporting. The OOC Button does not work while alive

**Comment by Wintermote** [comment]
That must be recent then, I'd been using it fine for the past week while alive at round end...
