### ISSUE TITLE
[BUG] the new bog map doesnt have daylight

### ISSUE THREAD

**Issue by erik30015** [Blackstone-SS13/BLACKSTONE#626]
## Describe the bug

before the bog map change, the day and night system affected if there was sunlight or if it was dark, now its just permanent darkness, as if it were always night

## Steps to Reproduce:

wait for time to transcur
its always dark in the outside, regardless of time(at least in the bog map)

**Comment by NPC1314** [comment]
Tested locally and sunlight does not appear to work at all, on the town z-level.
Tried adding subtypes of the outdoors areas but didn't do jack, someone broke the sun if it ever worked properly to start with

**Comment by Wintermote** [comment]
On the old bog map, I could see a difference between day and night, but nowhere else did it seem to work and the new bog map it definitely doesn't work.
