### ISSUE TITLE
[BUG] Downed zombies able to auto bite throat/head

### ISSUE THREAD

**Issue by Gyrandola** [Blackstone-SS13/BLACKSTONE#635]
## Describe the bug
I haven't tried to reproduce it yet but I woke up with this thought today and I vaguely recall this happening so yeah.

## Steps to Reproduce:
Get near a downed zombie.

## Additional context
Possible dreamworld misinformation.

**Comment by CVSthePharmacy** [comment]
they can't reach, also iirc they autoswitch to your left leg when they fall
