### ISSUE TITLE
[BUG] Unable to enter spirit world after rejoining as ghost.

### ISSUE THREAD

**Issue by Gyrandola** [Blackstone-SS13/BLACKSTONE#649]
## Describe the bug

This is the second time I die, rejoin the server some time later and find myself stuck in ghost mode. Clicking the "Journey to the underworld" button gives me the Yes - No prompt but it does not work.

## Steps to Reproduce:

1) Die.
2) Restart game.
3) Try to enter spirit world.

**Comment by ChungusGamer666** [comment]
seems solved
