### ISSUE TITLE
[REQUEST] Disguise skill to solve the rogue/beggar getting killed on examine

### ISSUE THREAD

**Issue by OrbitalParadise** [Blackstone-SS13/BLACKSTONE#682]
Rogues and beggars get a new skill called disguise, this skill gives you a prompt to change your examine name from a rogue to common role options, like towner, bog guard, town guard, castle guard, soilson, beggar, acolyte. 

There also could be a check in the code to see if you have at least 1 piece of clothing to make the initial disguise. After disguise creation, even if you take off your clothes you will still show up as the disguised job name on examine. 

If you change from 1 disguise to another, people who know you in the heart can see that you previously were a ____ and now you are a ____

**Comment by YosemiteYam** [comment]
Nah fuck that, it's accurate that your real world experiences/skill reflect on who you are when examined. How else am I going to gank piece of shit necromancers on sight

**Comment by OrbitalParadise** [comment]
never said necro's get this

**Comment by CVSthePharmacy** [comment]
close this
