### ISSUE TITLE
Steward and merchant issues

### ISSUE THREAD

**Issue by Coldstrike30** [Blackstone-SS13/BLACKSTONE#72]
The merchants shop doesnt have a navigator (the thing that is used to sell stuff)

**Comment by Coldstrike30** [comment]
Sorry more issues, the stewards place is supposed to resemble the format of the old map where the shylock and stockpile is available to everyone. now the shylock and stockpile are like in the gatehouse rooms which just makes it more un reachable.

**Comment by BlueMemesauce** [comment]
what map are these issues on

**Comment by TopHatPenguin** [comment]
#79 Merchant's navigator will be re-added soontm
