### ISSUE TITLE
[Request] Remove the tier 2 and tier 3 Necra spell from all the clerics

### ISSUE THREAD

**Issue by Zelda-Suchti** [Blackstone-SS13/BLACKSTONE#738]
## About The Pull Request

I noticed that every cleric regardless of their Patron get the Spell "Churn undead" (250 Devotion) and "Speak with souls" (500 Devotion) as free starting spell, without the need to pray for them, plus their 4 Spells of their Patron.

## Why It's Good For The Game
Balancing the Clerics which have already higher stats than an acolyte. They shouldn't have 6 Spells when they are not Necra Worthshippers. (Necra clerics have only 4 spells)

**Comment by Wozzy09** [comment]
Not all clerics, life cleric subtype can get them but its rng

**Comment by Zelda-Suchti** [comment]
i got them as life cleric 3 times in a row. i dont see the RNG so far... wait i try it again.

Churn undead is there (messed abit up and choose necra cleric, but its my first spell, so its still a starting spell as cleric itself)

**Comment by Knightfall5** [comment]
It's just RNG, the life cleric gets free additional spells in exchange for less combat skills. Which ones you get is random

**Comment by Zelda-Suchti** [comment]
alright.

**Comment by Zelda-Suchti** [comment]
is it possible to give the Clerics a lite version of this spell? It doesnt feel right that any chance of a good fight depens that there is no random cleric with this spell. Some days ago there were 5 Death knights at the Bog gate. One churn undead put them all on the floor and they were owned by 3 Bog guards, since they couldnt stand back up anymore.

**Comment by Knightfall5** [comment]
Death knights should be sticking close to their vampire lord for protection, if you stray away from them you risk getting hit with churn undead. If you use churn undead with a vampire lord on screen you are stunned and sent flying into the vampire lord which is basically instant death.

**Comment by ChungusGamer666** [comment]
to be done soon

**Comment by ChungusGamer666** [comment]
i dont think this is how this currently works whatsoever
