### ISSUE TITLE
[REQUEST] The Bog Guard Skillening. 

### ISSUE THREAD

**Issue by GreenHoodiedEthan** [Blackstone-SS13/BLACKSTONE#752]
## About the Pull Request

The newest training changes have left the bog guard in a strange place. Normally, their lackluster skills could be aided by a training dummy to whip them into fighting shape. However, this has come with the downside of people grinding themselves up to an absurd skill level. Then, yeeting themselves into the fray with Legendary combat skills. Now that this has been nerfed, the bog guard has been left behind in the dust. They are rather shoe-horned into the skills they start with, and deviating from the sword or bow isn't really beneficial.

Therefore, I suggest these changes. They don't have to all go through, but it would allow more variety in the Bog Guard.
1. Give the Bog Guard a Polearm Skill
2. Set all of Bog Guard's Combat Skills to either 2 or (2, 2, 3).
3. Optionally, also give the Bog Guard a Flail Skill

## Why it's good for the game

The main benefit of this is to switch up the armaments of the bog guard. The Bog were normally meant to be a rag-tag militia defending one of Rockhill's most dangerous checkpoints. This varies the weaponry of the Bog Guard and allows them to use other weapons. The Bog Guard can consult more varied professionals (Warriors, Clerics, Paladins or the Village Elder) for more training in a specific weapon. Spears and maces are also present in the armory, which would allow for the guards to swap to different weapons if they so choose.

Overall, the change is meant to make the Bog Guard more flexible with their weapon choices.

**Comment by ChungusGamer666** [comment]
To be clear, village elder is supposed to be the dedicated bog guard trainer.

**Comment by GreenHoodiedEthan** [comment]
The Village Elder can only train people in polearms and then axes & maces. The generic bog guard does not start with polearm skill, and also only starts with 1 skill level of axes & maces. Also, the Village Elder can only train so many people at a time before their body gives in.

I mostly want to give guards a better baseline for training, and then give them some leeway for what weapons they decide to choose at the start of a round.

**Comment by GreenHoodiedEthan** [comment]
The most recent changes to the Bog Guard are mostly what I want out of this, but I'm surprised at that substantial buff they got. Regardless, I'm thankful for the change.
