### ISSUE TITLE
[BUG] cant play as goblin

### ISSUE THREAD

**Issue by erik30015** [Blackstone-SS13/BLACKSTONE#817]
so uh

## Describe the bug

I think you need to have the goblin race to play as it, but I seem unable to select goblin, as it doesnt appear as a race, and the goblin role is race locked.

**Comment by wgtjunior743** [comment]
[https://github.com/Blackstone-SS13/BLACKSTONE/pull/783](url)

[https://github.com/Blackstone-SS13/BLACKSTONE/pull/763](url)

It is not a bug, look at these PR, goblin is just in WIP you can't really play as one yet, i don't even know if they will get their own game mode or something.
