### ISSUE TITLE
[BUG] Infinite roles like prisoner and beggar dont show up in preference menu

### ISSUE THREAD

**Issue by BlueMemesauce** [Blackstone-SS13/BLACKSTONE#824]
## Describe the bug

they dont show up

## Round ID:

all rounds

## Steps to Reproduce:

1. try to be beggar or prisoner at round start
2. cant

## Additional context

probably related to code with assistants being unlimited and the yes/no thing with assistants

**Comment by ChungusGamer666** [comment]
This has been fixed.
