### ISSUE TITLE
[BUG] Knight spawn issue

### ISSUE THREAD

**Issue by Yellows91** [Blackstone-SS13/BLACKSTONE#842]
## Additional context

This might be a one round only issue thing but making knights follow the rest of the garrison roles and be a "Late join" possibility would be the best fix for this if slop codes strikes again

**Comment by Gyrandola** [comment]
I dont think knights should be late joinable

**Comment by CVSthePharmacy** [comment]
I think knights should be late joinable

**Comment by awpenh** [comment]
Can confirm this bug occurred yesterday with no knights being rolled and opening slots didn't work since knights cannot late join.

Knights are almost always rolled anyway so I think having them late join is fine when issues like this occur

**Comment by ChungusGamer666** [comment]
Possibly fixed.
