### ISSUE TITLE
[REQUEST] It'd be nice if people could see who they should prioritize reviving.

### ISSUE THREAD

**Issue by pilotmans** [Blackstone-SS13/BLACKSTONE#873]
Being buried after waiting an hour to be revived cause people automatically thought you already left your body is fucking stupid.

## Add an indicator, perhaps for acolytes and clerics that upon examining a dead body to see if somebody is still in there.
maybe something similar to what TG station has.

**Comment by wgtjunior743** [comment]
Actually the span of time to be revived is very quick within 5 minutes your body will rot, and if you stay inside the body you will become a zombie, atleast like that you can be rot cure, but a roting body can't be cured and will eventually become a npc zombie or remains.
From my experience the priest and everyone will try to revive a non rotting body but once it rots, it will be buried, there is no salvation from that.

**Comment by pilotmans** [comment]
> Actually the span of time to be revived is very quick within 5 minutes your body will rot, and if you stay inside the body you will become a zombie, atleast like that you can be rot cure, but a roting body can't be cured and will eventually become a npc zombie or remains. From my experience the priest and everyone will try to revive a non rotting body but once it rots, it will be buried, there is no salvation from that.

The nature of Space Station-13 gameplay makes time limited revive systems not only annoying but also infuriating.

**Comment by ChungusGamer666** [comment]
Hugboxing, reviving someone should be a gamble
