### ISSUE TITLE
Invisible Bodies

### ISSUE THREAD

**Issue by TopHatPenguin** [Blackstone-SS13/BLACKSTONE#88]
Managed to trigger it with decapitation but it also happens with just hitting them.

- Hit undead or dead body and keep hitting
- The body goes invisible

can also simply be:
- find dead body and decapitate
- body is invisible but the head is fine

**Comment by NGGJamie** [comment]
Seems to be related to this:

```
runtime error: Too many overlays on /mob/living/carbon/human - 111, refusing to update and cutting
proc name: stack trace (/datum/proc/stack_trace)
  source file: code/__HELPERS/unsorted.dm,1243
  usr: null
  src: Overlay (/datum/controller/subsystem/overlays)
  call stack:
Overlay (/datum/controller/subsystem/overlays): stack trace("Too many overlays on /mob/livi...")
Overlay (/datum/controller/subsystem/overlays): fire(0, 1)
Overlay (/datum/controller/subsystem/overlays): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```

**Comment by JTGSZ** [comment]
Its related to that, currently when one mob attacks another they get overlays added on. This can stack infinitely which can bring them over 100 causing the icons to get cut making them iconless, thanks to a recent check added to the overlays SS.

**Comment by NGGJamie** [comment]
This was fixed.
