### ISSUE TITLE
[REQUEST] remove crits plz:3

### ISSUE THREAD

**Issue by painsufferinganguish** [Blackstone-SS13/BLACKSTONE#886]
it's not fun being insta killed and or wounded to a point where u get knocked out to be determined by a random numbah

and it's not fun when u gang up on someone, he's missing 5 eyes 4 legs, his entire lower body to then be killed urself by a critical hit 000.1 seconds later

**Comment by wgtjunior743** [comment]
Me when i crit the vampire lord in the eyes (he becomes ashes)

**Comment by pilotmans** [comment]
This is probably a good idea, having significantly disadvantaged foes beat a superior opponent in not only stats but also skill due to a "crit." is not fun.

**Comment by hivemuscle** [comment]
man spitting facts, rng combat is not good for fragging nor roleplay
but you can't just remove crits, entire battle system, it's intents, are balanced on them and need to be reworked

**Comment by ChungusGamer666** [comment]
crits are fundamental to combat as it stands right now and removing them would require reworking medical entirely
