### ISSUE TITLE
[BUG] Waterskins cannot be crafted

### ISSUE THREAD

**Issue by pilotmans** [Blackstone-SS13/BLACKSTONE#893]
Waterskins will not appear inside of the crafting menu even if you have all the recipes materials and a drying rack

even facing a table will not help you
the only time i ever saw it on the crafting menu was when i was facing a table with the drying rack directly behind me, but at that point,
i couldn't use the drying rack meaning i couldn't craft it.

**Comment by Hmeister-real** [comment]
you had 3 hide, and two fibre right? I may just make it a little cheaper while im looking at it

**Comment by Hmeister-real** [comment]
from what i saw, nothing should be wrong with the craft? made #965 which makes them cheaper, maybe you just didn't have the skin to craft it

**Comment by pilotmans** [comment]
> from what i saw, nothing should be wrong with the craft? made #965 which makes them cheaper, maybe you just didn't have the skin to craft it

I think what might have been the problem was it not appearing on the crafting menu due to all of the other recipes taking up too much space.

**Comment by pilotmans** [comment]
So, it should be fixed, but I'll test it as soon as I can.
