### ISSUE TITLE
[BUG] Unexpected Behavior for dungoneer confession

### ISSUE THREAD

**Issue by Wirpy** [Blackstone-SS13/BLACKSTONE#908]
I double grab X person, press extract confession the prompt for resist confession appears to pay 1 triumph and only option is yes. 
It stopped me from talking, moving etc until I pressed yes and paid the 1 triumph ( allegedly) I haven't seen if I lost triumph syet casue its still current round as of writing. 

## Round ID:

Saiga351-11.45.08
## Steps to Reproduce:

Just grab someone and extract confession as dungoneer

**Comment by Wintermote** [comment]
Possibly grabbed yourself?

**Comment by ChungusGamer666** [comment]
fixed
