### ISSUE TITLE
[REQUEST] Castle Guard Swords

### ISSUE THREAD

**Issue by Yellows91** [Blackstone-SS13/BLACKSTONE#924]
## Is your feature request related to a problem? Please describe. 
Castle guard steel swords got removed forcing all of them to either use their spear or pray that they can get a good deal at the weaponsmith to get it moved over.

## Describe the solution you'd like
Give Castle guard their Steel sword back

## Describe alternatives you've considered
None.

## Additional context
In all seriousness I don't understand why we removed steel sword from Castle guard.

The spear cannot be put on the back and is big and clunky and usually not great when it comes to most things while the sword can be put in a hip slot and isn't bulky and pretty universal in combat.

**Comment by Yellows91** [comment]
Turns out the spear is made out of iron so you can't even convert it into a steel sword. Serious downgrade from original loadout they had.

**Comment by ChungusGamer666** [comment]
Their gear has been upgraded in other ways. They are called men at arms hence they get a spear.

**Comment by BlueMemesauce** [comment]
they used spears when they were on horses but they dont get horses
