### ISSUE TITLE
[BUG] No cutscene when maniac wins.

### ISSUE THREAD

**Issue by rhailrake** [Blackstone-SS13/BLACKSTONE#944]
## Describe the bug

No cutscene when maniac wins.

Admin told me to do an issue.

Admin PM from-Wow50000: thats weird you are meant to see a cutscene

## Round ID:

Spider369-06.35.42

## Steps to Reproduce:

Win as a maniac.

## Additional context
![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/49613070/50c823c4-caee-4f3d-861e-9b221afd4770)

**Comment by fiercestwarrior** [comment]
not a bug, the cyberdeck helmet obscures your vision

**Comment by ChungusGamer666** [comment]
not a bug you didn't take the helmet off
