### ISSUE TITLE
[REQUEST] SCOM Law Announcement

### ISSUE THREAD

**Issue by GreenHoodiedEthan** [Blackstone-SS13/BLACKSTONE#952]
This is a simple change, it allows those without the ability to read to go off to an SCOM and "request laws." The SCOM will then list all of the logs that king/baliff has currently instated. This is mostly beneficial to beggars and the such who can't read. 

Nothing too fancy.

**Comment by BlueMemesauce** [comment]
You have to read to understand them, he's talking about a command for illiterate people where the machine will state laws if you ask it to "state laws"

**Comment by GreenHoodiedEthan** [comment]
I figured out this was a feature, I did not know existed.
