### ISSUE TITLE
[BUG] Druggy eyecolor effects stay forever

### ISSUE THREAD

**Issue by gitbirb** [Blackstone-SS13/BLACKSTONE#971]
## Describe the bug

After snorting Spice or smoking Swampweed, your eye color starts flashing rainbow.
However, once the drug's effects concludes, your eye color is still flashing rainbow, when it should return to default.

Afaik this is permanent, which kind of sucks.

## Round ID:

Happened over many rounds

## Steps to Reproduce:

1. Grab a swampweed zig from the PURITY vendor.
2. Light er' up
3. Put it in your mouth
     * Now your eyes are constantly flashing rainbow
4. Take it out of your mouth once you get the drug effect
5. Wait for the drug effect to wear off

     * Looks like the eye color effect stayed longer then expected
6. The eye color rainbow effect stays forever

**Comment by ChungusGamer666** [comment]
Confirmed. This has happened to me.
